name: PR

on:
  push:
    branches: [main]
  pull_request_target:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  example:
    name: Uniswap example
    runs-on:
      [
        runs-on,
        cpu=64,
        ram=256,
        family=m7i+m7a,
        hdd=80,
        image=ubuntu22-full-x64,
        spot=false,
        "run-id=${{ github.run_id }}",
      ]    
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: "Install sp1up"
        run: |
            curl -L https://sp1.succinct.xyz | bash
            echo "$HOME/.sp1/bin" >> $GITHUB_PATH

      - name: "Install SP1 toolchain"
        run: |
            sp1up

      - name: "Set up RPC env"
        run: |
          echo "ETH_RPC_URL=${{secrets.ETH_RPC_URL}}" >> $GITHUB_ENV

      - name: Run uniswap script
        uses: actions-rs/cargo@v1   
        with:
          command: run
          args:
            --release --bin uniswap --ignore-rust-version
        env:
          RUSTFLAGS: -Copt-level=3 -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: full
          RUST_LOG: info

  test-e2e:
    name: E2E tests
    runs-on: ["runs-on", "runner=32cpu-linux-x64", "run-id=${{ github.run_id }}"]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Set up RPC env"
        run: |
          echo "ETH_RPC_URL=${{secrets.ETH_RPC_URL}}" >> $GITHUB_ENV
          echo "ETH_SEPOLIA_RPC_URL=${{secrets.ETH_SEPOLIA_RPC_URL}}" >> $GITHUB_ENV

      - name: "Run integration test"
        run: |
          SP1_DEV=1 RUST_LOG=info cargo test -p sp1-cc-host-executor --release -- --nocapture

  test-uniswap-forge:
    name: Test uniswap forge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd examples/uniswap/contracts
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd examples/uniswap/contracts
          forge test -vvv
        id: test
