name: PR

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "crates/**"
      - "examples/**"
      - "Cargo.toml"
      - ".github/workflows/**"
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    name: Examples
    runs-on: ["runs-on", "runner=64cpu-linux-x64", "run-id=${{ github.run_id }}"]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: "Install sp1up"
        run: |
            curl -L https://sp1.succinct.xyz | bash
            echo "$HOME/.sp1/bin" >> $GITHUB_PATH

      - name: "Install SP1 toolchain"
        run: |
            sp1up

    #   - name: Install SP1 toolchain
    #     run: |
    #       curl -L https://sp1.succinct.xyz | bash
    #       ~/.sp1/bin/sp1up 
    #       ~/.sp1/bin/cargo-prove prove --version

    #   - name: Install SP1 CLI
    #     run: |
    #       cd crates/cli
    #       cargo install --force --locked --path .
    #       cd ~

      - name: Run uniswap script
        run: |
          SP1_DEV=1 RUST_LOG=info cargo run --release --bin uniswap --ignore-rust-version   

      - name: Run multiplexer script
        run: |
          SP1_DEV=1 RUST_LOG=info cargo run --release --bin multiplexer --ignore-rust-version

