name: PR

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "crates/**"
      - "examples/**"
      - "Cargo.toml"
      - ".github/workflows/**"
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  multiplexer:
    name: Multiplexer
    runs-on: ["runs-on", "runner=64cpu-linux-x64", "run-id=${{ github.run_id }}"]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd crates/cli
          cargo install --force --locked --path .
          cd ~

      - name: Run tendermint script
        run: |
          cd examples/tendermint/program
          cargo add sp1-zkvm --path $GITHUB_WORKSPACE/crates/zkvm/entrypoint
          cargo prove build
          cd ../script
          cargo remove sp1-sdk
          cargo add sp1-sdk --path $GITHUB_WORKSPACE/crates/sdk
          SP1_DEV=1 RUST_LOG=info cargo run --release

